baseURL = "https://samyaks.xyz"
languageCode = "en-us"
title = "Samyak Sarnayak"

theme = "gruvhugo"

paginate = "10" # Number of posts per page

# enable shortcodes like css.inline
enableInlineShortcodes = true

# automatically updates last modified based on git
enableGitInfo = true


[frontmatter]
  lastmod = ['lastmod', ':git', 'date', 'publishDate']


# from gruvhugo
[taxonomies]
  tag      = "tags"
  category = "categories"
  series   = "series"

[params.main]
  enabled = true
  enableKatex = true
  metaKeywords = "Samyak, Sarnayak, PES, Software"
  headerTitle = "Samyak Sarnayak"
  copyright = "© 2021-2022 Samyak Sarnayak.  <a href=\"https://creativecommons.org/licenses/by-nc-sa/4.0/\">Some rights reserved</a>."
  name = "samyak_sarnayak"
  img = "images/mob.png"
  img_title = "Mob-kun, traced by me over the original. Someday I will draw him myself."
  icon = "img/logo.png"
  quote = "🦏"
  description= "Hello there. I'm Samyak Sarnayak. I like systems and programming languages."
  licenseUrl = ""

 # Social icons
  [[params.social]]
    name = "github"
    url  = "https://github.com/Samyak2"

  # [[params.social]]
  #   name = "gitlab"
  #   url  = "https://gitlab.com/samyaks"

  [[params.social]]
    name = "email"
    url  = "mailto:samyak201@gmail.com"

  # [[params.social]]
  #   name = "gpg"
  #   url  = "https://keys.openpgp.org/"

  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/Samyak210"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/samyaks"

[params.style]
  custom_scss = ["/sass/custom.scss"]

[params.analytics]
  goat_counter_link = "https://samyak.goatcounter.com/count"

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About me"
    url        = "about"

  [[menu.main]]
    identifier = "posts"
    name       = "Blog"
    url        = "post/"

  [[menu.main]]
    identifier = "projects"
    name       = "Projects"
    url        = "projects"

  [[menu.main]]
    identifier = "cv"
    name       = "CV"
    url        = "cv.pdf"

  [[menu.main]]
    identifier = "research"
    name       = "Research"
    url        = "research"

[permalinks]
  post = '/:section/:slug'

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "dracula"
    tabWidth = 4
